name: Unit Test

on:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Unit Test
        run: yarn test

      - name: Automerge
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: ''
          MERGE_METHOD: squash
